### ISSUE TITLE
how can I Add language

### ISSUE THREAD

**Issue by sachintechknocks** [israel-dryer/Steam-Game-Review-Scraper#1]
Is there a way to add language type and include all languages of the game review

**Comment by israel-dryer** [comment]
In all honesty, I would recommend checking out the Steam Review API. I didn't know about it when I quickly built this. But, it's got a LOT more meta data available, and is a much quicker and easier solution.
https://github.com/woctezuma/download-steam-reviews

**Comment by israel-dryer** [comment]
I added a language filter to the script. Also, I fixed the loop as it was not breaking when completed. While you can't get the language directly, you can filter by a specific language. So, if you were to run the program for each language in a list of languages, you could essentially get the same results by tagging each batch with that language name.
